#!/usr/bin/env python3
"""
build_skill_snapshots.py — freeze the three DQE evaluator bundles Phase E compares.

Per DQE_D3决策与PhaseE安全准入计划 §2.2, the admission matrix must run each arm from a byte-frozen,
hash-recorded bundle, NOT from a hand-reconstructed "revert v0.4 to v0.3". Each bundle is extracted from a
real source (a git commit, or the working tree for the candidate) so the comparison is reproducible.

Bundles:
  dqe-v0.3.0            <- git 279c0ce   (pre-v0.4, single-axis DOCUMENT_QUALITY evaluator)
  dqe-v0.4.0-pre-d16    <- git 14959a8   (two-axis, profile-aware HF-9; BEFORE the D-16 gate fix)
  dqe-v0.4.1-candidate  <- working tree  (D-16 fix + version bump to 0.4.1)

Each bundle contains:
  SKILL.md hard-fail.md rubric.md canonical-source-map.md  (the injected evaluator context)
  EVALUATOR_CONTRACT.txt        (the role=evaluator preamble, ast-extracted from make_grading_injection.py)
  checker-manifest.yaml         (the checker set — HELD CONSTANT across arms at live HEAD; hashes recorded)
  SNAPSHOT-MANIFEST.yaml        (version, source_commit, created_at, per-file sha256)

Checkers are deterministic raw-finding producers; the experiment varies only the SKILL + EVALUATOR_CONTRACT
(the thing under test) and holds the checker layer fixed at the live set. That is recorded explicitly so a
later reader knows the checker layer was controlled, not silently drifting.

Usage: python scripts/build_skill_snapshots.py [--date 2026-08-05]
"""
from __future__ import annotations
import ast
import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAP = ROOT / "evals" / "skills" / "snapshots"
SKILL_REL = ".agents/skills/documentation-quality-evaluator/SKILL.md"
HARNESS_REL = "evals/skills/harness"
MGI_REL = f"{HARNESS_REL}/make_grading_injection.py"
CTX_FILES = ["hard-fail.md", "rubric.md", "canonical-source-map.md"]
# the live checker set is held constant across arms; recorded for provenance
CHECKER_DIR = ROOT / HARNESS_REL / "checkers"

BUNDLES = [
    ("dqe-v0.3.0", "279c0ce", "0.3.0"),
    ("dqe-v0.4.0-pre-d16", "14959a8", "0.4.0-pre-d16"),
    ("dqe-v0.4.1-candidate", "WORKTREE", "0.4.1"),
]


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def read_source(ref: str, rel: str) -> bytes:
    """Read a file either from a git commit (ref) or the working tree (ref=='WORKTREE')."""
    if ref == "WORKTREE":
        return (ROOT / rel).read_bytes()
    out = subprocess.run(["git", "show", f"{ref}:{rel}"], cwd=ROOT,
                         capture_output=True)
    if out.returncode != 0 and rel.startswith(".agents/"):
        # Historical commits predate the 2026-09-09 `.claude` -> `.agents` rename.
        legacy = ".claude/" + rel[len(".agents/"):]
        out = subprocess.run(["git", "show", f"{ref}:{legacy}"], cwd=ROOT,
                             capture_output=True)
    if out.returncode != 0:
        raise SystemExit(f"git show {ref}:{rel} failed: {out.stderr.decode('utf-8','replace')[:200]}")
    return out.stdout


def extract_evaluator_contract(mgi_src: str) -> str:
    """ast-extract the module-level EVALUATOR_CONTRACT string literal."""
    tree = ast.parse(mgi_src)
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == "EVALUATOR_CONTRACT":
                    return ast.literal_eval(node.value)
    raise SystemExit("EVALUATOR_CONTRACT not found in make_grading_injection.py")


def live_checker_manifest() -> tuple[str, list[dict]]:
    """Hash the live checker set (held constant across arms)."""
    entries = []
    for p in sorted(CHECKER_DIR.glob("*.py")):
        b = p.read_bytes()
        entries.append({"path": f"checkers/{p.name}", "sha256": sha256_bytes(b)})
    combined = sha256_bytes("".join(e["sha256"] for e in entries).encode())
    return combined, entries


def yaml_manifest(version: str, source_commit: str, created_at: str,
                  files: list[dict], checker_combined: str, checkers: list[dict]) -> str:
    lines = [
        "# Frozen DQE evaluator bundle — Phase E admission arm.",
        "# Generated by scripts/build_skill_snapshots.py; do not hand-edit.",
        f"version: {version}",
        f"source_commit: {source_commit}",
        f"created_at: {created_at}",
        "checker_layer: live-HEAD (held constant across all arms; varied component is SKILL+EVALUATOR_CONTRACT only)",
        f"checker_set_sha256: {checker_combined}",
        "files:",
    ]
    for f in files:
        lines += [f"  - path: {f['path']}", f"    sha256: {f['sha256']}"]
    lines.append("checkers:")
    for c in checkers:
        lines += [f"  - path: {c['path']}", f"    sha256: {c['sha256']}"]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    created_at = argv[argv.index("--date") + 1] if "--date" in argv else "2026-08-05"
    checker_combined, checkers = live_checker_manifest()
    SNAP.mkdir(parents=True, exist_ok=True)

    for name, ref, version in BUNDLES:
        out = SNAP / name
        out.mkdir(parents=True, exist_ok=True)
        files: list[dict] = []

        def emit(rel_name: str, data: bytes):
            (out / rel_name).write_bytes(data)
            files.append({"path": rel_name, "sha256": sha256_bytes(data)})

        emit("SKILL.md", read_source(ref, SKILL_REL))
        for cf in CTX_FILES:
            emit(cf, read_source(ref, f"{HARNESS_REL}/{cf}"))
        mgi_src = read_source(ref, MGI_REL).decode("utf-8", "replace")
        contract = extract_evaluator_contract(mgi_src)
        emit("EVALUATOR_CONTRACT.txt", contract.encode("utf-8"))

        src_label = "working-tree (post-D-16, version-bumped 0.4.1; base HEAD=0585574)" if ref == "WORKTREE" else ref
        (out / "checker-manifest.yaml").write_text(
            "# checker set held constant across arms (live HEAD). Recorded for provenance.\n"
            f"checker_set_sha256: {checker_combined}\n"
            + "".join(f"- {c['path']}: {c['sha256']}\n" for c in checkers), encoding="utf-8")
        (out / "SNAPSHOT-MANIFEST.yaml").write_text(
            yaml_manifest(version, src_label, created_at, files, checker_combined, checkers), encoding="utf-8")

        # verdict-axis fingerprint so a reader can see the arm's shape at a glance
        skill_txt = (out / "SKILL.md").read_text(encoding="utf-8", errors="replace")
        two_axis = "GATE_DECISION" in skill_txt and "QUALITY_BAND" in skill_txt
        d16 = "do NOT improvise" in skill_txt
        print(f"  {name:24s} src={src_label[:28]:28s} two_axis={two_axis} d16={d16} files={len(files)}")

    print(f"\n==> wrote {len(BUNDLES)} snapshots under {SNAP.relative_to(ROOT).as_posix()}/")
    print(f"    checker_set_sha256 (constant across arms) = {checker_combined[:16]}...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
